<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

/**
 * @method static self first()
 * @method static self find($id)
 * @method static self where(string $column, mixed $value)
 */
class Contact extends Model
{
    use Sushi;

    public $fillable = [
        'name',
        'phone',
        'address',
    ];
    protected $rows = [
        [
            "id" => 1,
            "name" => "James Rodrigues 1",
            "phone" => "+628130000001",
            "address" => "Jl Example No. 1, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 2,
            "name" => "James Rodrigues 2",
            "phone" => "+628130000002",
            "address" => "Jl Example No. 2, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 3,
            "name" => "James Rodrigues 3",
            "phone" => "+628130000003",
            "address" => "Jl Example No. 3, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 4,
            "name" => "James Rodrigues 4",
            "phone" => "+628130000004",
            "address" => "Jl Example No. 4, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 5,
            "name" => "James Rodrigues 5",
            "phone" => "+628130000005",
            "address" => "Jl Example No. 5, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 6,
            "name" => "James Rodrigues 6",
            "phone" => "+628130000006",
            "address" => "Jl Example No. 6, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 7,
            "name" => "James Rodrigues 7",
            "phone" => "+628130000007",
            "address" => "Jl Example No. 7, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 8,
            "name" => "James Rodrigues 8",
            "phone" => "+628130000008",
            "address" => "Jl Example No. 8, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 9,
            "name" => "James Rodrigues 9",
            "phone" => "+628130000009",
            "address" => "Jl Example No. 9, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 10,
            "name" => "James Rodrigues 10",
            "phone" => "+628130000010",
            "address" => "Jl Example No. 10, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 11,
            "name" => "James Rodrigues 11",
            "phone" => "+628130000011",
            "address" => "Jl Example No. 11, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 12,
            "name" => "James Rodrigues 12",
            "phone" => "+628130000012",
            "address" => "Jl Example No. 12, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 13,
            "name" => "James Rodrigues 13",
            "phone" => "+628130000013",
            "address" => "Jl Example No. 13, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 14,
            "name" => "James Rodrigues 14",
            "phone" => "+628130000014",
            "address" => "Jl Example No. 14, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 15,
            "name" => "James Rodrigues 15",
            "phone" => "+628130000015",
            "address" => "Jl Example No. 15, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 16,
            "name" => "James Rodrigues 16",
            "phone" => "+628130000016",
            "address" => "Jl Example No. 16, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 17,
            "name" => "James Rodrigues 17",
            "phone" => "+628130000017",
            "address" => "Jl Example No. 17, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 18,
            "name" => "James Rodrigues 18",
            "phone" => "+628130000018",
            "address" => "Jl Example No. 18, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 19,
            "name" => "James Rodrigues 19",
            "phone" => "+628130000019",
            "address" => "Jl Example No. 19, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 20,
            "name" => "James Rodrigues 20",
            "phone" => "+628130000020",
            "address" => "Jl Example No. 20, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 21,
            "name" => "James Rodrigues 21",
            "phone" => "+628130000021",
            "address" => "Jl Example No. 21, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 22,
            "name" => "James Rodrigues 22",
            "phone" => "+628130000022",
            "address" => "Jl Example No. 22, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 23,
            "name" => "James Rodrigues 23",
            "phone" => "+628130000023",
            "address" => "Jl Example No. 23, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 24,
            "name" => "James Rodrigues 24",
            "phone" => "+628130000024",
            "address" => "Jl Example No. 24, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 25,
            "name" => "James Rodrigues 25",
            "phone" => "+628130000025",
            "address" => "Jl Example No. 25, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 26,
            "name" => "James Rodrigues 26",
            "phone" => "+628130000026",
            "address" => "Jl Example No. 26, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 27,
            "name" => "James Rodrigues 27",
            "phone" => "+628130000027",
            "address" => "Jl Example No. 27, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 28,
            "name" => "James Rodrigues 28",
            "phone" => "+628130000028",
            "address" => "Jl Example No. 28, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 29,
            "name" => "James Rodrigues 29",
            "phone" => "+628130000029",
            "address" => "Jl Example No. 29, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 30,
            "name" => "James Rodrigues 30",
            "phone" => "+628130000030",
            "address" => "Jl Example No. 30, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 31,
            "name" => "James Rodrigues 31",
            "phone" => "+628130000031",
            "address" => "Jl Example No. 31, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 32,
            "name" => "James Rodrigues 32",
            "phone" => "+628130000032",
            "address" => "Jl Example No. 32, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 33,
            "name" => "James Rodrigues 33",
            "phone" => "+628130000033",
            "address" => "Jl Example No. 33, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 34,
            "name" => "James Rodrigues 34",
            "phone" => "+628130000034",
            "address" => "Jl Example No. 34, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 35,
            "name" => "James Rodrigues 35",
            "phone" => "+628130000035",
            "address" => "Jl Example No. 35, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 36,
            "name" => "James Rodrigues 36",
            "phone" => "+628130000036",
            "address" => "Jl Example No. 36, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 37,
            "name" => "James Rodrigues 37",
            "phone" => "+628130000037",
            "address" => "Jl Example No. 37, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 38,
            "name" => "James Rodrigues 38",
            "phone" => "+628130000038",
            "address" => "Jl Example No. 38, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 39,
            "name" => "James Rodrigues 39",
            "phone" => "+628130000039",
            "address" => "Jl Example No. 39, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 40,
            "name" => "James Rodrigues 40",
            "phone" => "+628130000040",
            "address" => "Jl Example No. 40, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 41,
            "name" => "James Rodrigues 41",
            "phone" => "+628130000041",
            "address" => "Jl Example No. 41, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 42,
            "name" => "James Rodrigues 42",
            "phone" => "+628130000042",
            "address" => "Jl Example No. 42, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 43,
            "name" => "James Rodrigues 43",
            "phone" => "+628130000043",
            "address" => "Jl Example No. 43, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 44,
            "name" => "James Rodrigues 44",
            "phone" => "+628130000044",
            "address" => "Jl Example No. 44, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 45,
            "name" => "James Rodrigues 45",
            "phone" => "+628130000045",
            "address" => "Jl Example No. 45, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 46,
            "name" => "James Rodrigues 46",
            "phone" => "+628130000046",
            "address" => "Jl Example No. 46, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 47,
            "name" => "James Rodrigues 47",
            "phone" => "+628130000047",
            "address" => "Jl Example No. 47, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 48,
            "name" => "James Rodrigues 48",
            "phone" => "+628130000048",
            "address" => "Jl Example No. 48, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 49,
            "name" => "James Rodrigues 49",
            "phone" => "+628130000049",
            "address" => "Jl Example No. 49, City 12345",
            "is_deleted" => false,
        ],
        [
            "id" => 50,
            "name" => "James Rodrigues  50",
            "phone" => "+628130000050",
            "address" => "Jl Example No. 50, City 12345",
            "is_deleted" => false,
        ],
    ];

}
